### ISSUE TITLE
Code does not work with Async.

### ISSUE THREAD

**Issue by rohanmodil123** [george-lim/textnow-bot-python#1]
Slew of errors when this is attempted to be used asynchronously.

**Comment by rohanmodil123** [comment]
I have opened a pull request fixing this. It says "checks failed", but the linter has only detected stylistic issues, the code works fine.

**Comment by george-lim** [comment]
Yeah I took a look at the code, looks fine to me. I will test this tomorrow, and address the linter concerns.

**Comment by george-lim** [comment]
Hey @rohanmodil123 I have addressed this in my latest PR. Please give it a test and let me know if you like it.
I deployed it to TestPyPI: https://test.pypi.org/project/textnow-bot/1.0.5.dev1
